ItProject/ItProject/urls.py
from django.contrib import admin
from django.urls import path,include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
    path("user/",include("user.urls")),
    path("support/",include("itsupport.urls")),
]+ static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)   

ItProject/itsupport/urls.py
from django.urls import path
from .import views
app_name ="itsupport"


urlpatterns =[
    path("support/request/",views.support_request, name="support_request"),
    path("user/request/",views.user_request_view,name="user_request_view"),
    path("my/order/",views.my_order,name="my_order"),
    path("add/prenter/request",views.add_printer_request,name="add_printer_request"),
    path("request/detail/<request_id>",views.request_detail_view,name="request_detail_view"),
    path("close/order/<request_id>",views.close_order,name="close_order"),
    path("on/workv/",views.on_work_view ,name="on_work_view"),
    path("done/work/",views.done_work_view,name="done_work_view"),
    path("chating/<request_id>/",views.chating,name="chating")
]

ItProject/main/urls.py
from django.urls import path
from .import views
app_name = "main"


urlpatterns =[
    path("",views.home_view,name="home_view"),

]

ItProject/itsupport/models.py
from django.db import models
from django.contrib.auth.models import User

class MaintenanceRequest(models.Model):

    
    STATUS_CHOICES = [
        ('مفتوح','مفتوح' ),
        ( 'تحت الإجراء','تحت الإجراء'),
        
        ('منتهي','منتهي'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    device_type = models.CharField(max_length=255)
    device_id = models.CharField(max_length=100)
    problem_description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='مفتوح')
    request_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/',default="images/default.jpg")
    
    
    def __str__(self):
        return f'{self.device_type} - {self.device_id} ({self.user.username})'
    



class PrinterRequest(models.Model):

    
    STATUS_CHOICES = [
        ('مفتوح','مفتوح' ),
        ( 'تحت الإجراء','تحت الإجراء'),
        
        ('منتهي','منتهي'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    printer_type = models.CharField(max_length=255)
    printer_id = models.CharField(max_length=100)
    ink_id = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='مفتوح')
    request_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/',default="images/default.jpg")
    
    
    def __str__(self):
        return f'{self.printer_type} - {self.printer_id} ({self.user.username})'
    


class ItHelp(models.Model):

    it_employee = models.ForeignKey(User,on_delete=models.CASCADE)
    
    user_request = models.ForeignKey(MaintenanceRequest,on_delete=models.CASCADE)

    #user_request_p = models.ForeignKey(PrinterRequest,on_delete=models.CASCADE)



class PrinterHelp(models.Model):

    it_employee = models.ForeignKey(User,on_delete=models.CASCADE)
    

    user_request_p = models.ForeignKey(PrinterRequest,on_delete=models.CASCADE)





class Chat(models.Model):
    
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    content = models.TextField()

ItProject/itsupport/views.py
from django.shortcuts import render,redirect

from django.http import HttpRequest

from .models import MaintenanceRequest,PrinterRequest,ItHelp,PrinterHelp,Chat
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User
# Create your views here.


def send_order_status_email(recipient_email):
    subject = 'حالة الطلب'
    message = 'طلبك تحت الإجراء.'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [recipient_email]

    send_mail(subject, message, email_from, recipient_list)



def support_request(request:HttpRequest):
    msg=None
    user = User.objects.get(id=request.user.id)
    orders = MaintenanceRequest.objects.filter(user=user)
    is_there =True

    for order in orders:
        if order.status =='تحت الإجراء' or order.status =='مفتوح':
            is_there = False
            break
    
    
    if is_there:
    
        if request.user.is_authenticated:
            if request.method == "POST":
                user_request =MaintenanceRequest(
                    user=request.user,
                    device_type=request.POST["device_type"],
                    device_id=request.POST["device_id"],
                    problem_description =request.POST["problem_description"],
                    
                    )
                if "image" in request.FILES:
                    user_request.image =request.FILES["image"]
                    
                user_request.save()
                return redirect("itsupport:my_order")
        else:
            return redirect("user:login_view")
    else:
        msg="لايمكنك رفع طلب اخر حتى يغلق طلبك"


    return render(request,"itsupport/support_request.html",{"msg":msg})



def user_request_view(request:HttpRequest):
    if not request.user.is_staff:
        return redirect("main:home_view")

    user_request = MaintenanceRequest.objects.all()
    ink_requests = PrinterRequest.objects.all()

    

    return render(request,"itsupport/user_request.html",{"users_requests":user_request,"ink_requests":ink_requests})


def my_order(request:HttpRequest):
    user = User.objects.get(id=request.user.id)
    my_order = MaintenanceRequest.objects.filter(user=user)

    printer_order = PrinterRequest.objects.filter(user=user)
    
    

    return render(request,"itsupport/my_order.html",{"my_order":my_order,"printer_order":printer_order})



def add_printer_request(request:HttpRequest):

    if request.user.is_authenticated:
        if request.method == "POST":
            user_request =PrinterRequest(
                user=request.user,
                printer_type=request.POST["printer_type"],
                printer_id=request.POST["printer_id"],
                
                ink_id = request.POST["ink_id"]
                )
            if "image" in request.FILES:
                user_request.image = request.FILES["image"]
            user_request.save()
            return redirect("itsupport:my_order")
    else:
        return redirect("user:login_view")
    


    
def request_detail_view(request:HttpRequest,request_id):

    it_chat=None
    user_chat=None
    request_detail =None
    prenter_detail = None
    it_emp =None
    try:

            request_detail = MaintenanceRequest.objects.get(id=request_id)
            request_detail.user
            user_chat = Chat.objects.filter(user=request_detail.user)
            try:

                emp = ItHelp.objects.get(user_request=request_detail)
                it_chat = Chat.objects.filter(user=emp.it_employee)
            except:
                emp=None
    except:
            prenter_detail = PrinterRequest.objects.get(id=request_id)
            user_chat = Chat.objects.filter(user=prenter_detail.user)
            
            try:

                emp = PrinterHelp.objects.get(user_request_p=prenter_detail)
                it_chat = Chat.objects.filter(user=emp.it_employee)
            except:
                    emp=None
    if request.user.is_staff:

        try:
            user_email=request_detail.user.email
        except:
                user_email=prenter_detail.user.email
        if request.method == "POST":
            
            recipient_email = user_email
            try:
                it_emp = ItHelp(it_employee=request.user,user_request=request_detail)
                it_emp.save()
            except:
                    it_emp = PrinterHelp(it_employee=request.user,user_request_p=prenter_detail)
                    it_emp.save()
                

            send_order_status_email(recipient_email)
            try:
                request_detail.status = "تحت الإجراء"
                request_detail.save()
            except:
                    prenter_detail.status = "تحت الإجراء"
                    prenter_detail.save()

            return redirect("itsupport:request_detail_view",request_id)
            


    return render(request,"itsupport/request_detail.html",{"request_detail":request_detail,"prenter_detail":prenter_detail,"emp":emp,"user_chat":user_chat,"it_chat":it_chat})



def close_order(request:HttpRequest,request_id):
    request_detail =None
    prenter_detail = None

    try:

        request_detail = MaintenanceRequest.objects.get(id=request_id)
    except:
        prenter_detail = PrinterRequest.objects.get(id=request_id)


    if request.user.is_staff:

        
        
        if request.method == "POST":
            
            
            try:
                request_detail.status = 'منتهي'
                request_detail.save()
            except:
                prenter_detail.status = 'منتهي'
                prenter_detail.save()
            
            chat=Chat.objects.get(user=request.user)
            chat.delete()
            return redirect("itsupport:done_work_view")
        



def on_work_view(request:HttpRequest):

    work_on =MaintenanceRequest.objects.filter(status='تحت الإجراء')

    return render(request,"itsupport/on_work.html",{"work_on":work_on})



def done_work_view(request:HttpRequest):

    done_work =MaintenanceRequest.objects.filter(status="منتهي")


    return render(request,"itsupport/done_work.html",{"done_works":done_work})




def chating(request:HttpRequest,request_id):
    chat = None
    user_request=None
    it_employee =None
    try:
        user_request = MaintenanceRequest.objects.get(id=request_id)
        it = ItHelp.objects.get(user_request=user_request) 
        it_employee = it.it_employee
    except:
         user_request = PrinterRequest.objects.get(id=request_id)
         it = PrinterHelp.objects.get(user_request_p=user_request) 
         it_employee = it.it_employee
        


    user_req = user_request.user
    if request.user.is_authenticated:
        if request.method =="POST":
             if request.user == user_req:
                chat=Chat(user=user_req,content=request.POST["content"])
                chat.save()
             else:
                chat=Chat(user=it_employee,content=request.POST["content"])
                chat.save()
             

        return redirect("itsupport:request_detail_view",request_id)


     

ItProject/itsupport/templates/itsupport/done_work.html
{% extends 'main/base.html' %}

{% load static %}


{% block content %}
 
<style>
    .custom-container {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 20px;
        max-width: 1200px;
        margin: 50px auto;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .custom-table thead {
        background-color: #343a40;
        color: #ffffff;
    }
    .badge-status {
        border-radius: 4px;
        padding: 4px 8px;
        display: inline-block;
        font-size: 0.9em;
    }
    .badge-open {
        background-color: #e0f7fa;
        color: #28a745;
    }
    .badge-in-progress {
        background-color: #fff3cd;
        color: #ffc107;
    }
    .badge-closed {
        background-color: #f8d7da;
        color: #dc3545;
    }
    .btn-view-details {
        margin: 0;
    }
</style>
</head>
<body>

<div class="container mt-5">
<div class="custom-container">
    <h2 class="text-center mb-4">طلبات  منتهية</h2>
    <table class="table table-bordered table-striped table-hover custom-table">
        {% if done_works.count != 0 %}
        <thead>
            <tr>
                <th scope="col">اسم المستخدم</th>
                <th scope="col"> ايميل</th>
                <th scope="col">نوع الطلب</th>
                <th scope="col">تاريخ إنشاء الطلب</th>

               
            </tr>
        </thead>
        <tbody>
            
            
            {% for done in done_works%}
            <tr>
                <td>{{done.user.first_name}} {{done.user.last_name}}</td>
                <td>{{done.user.email}}</td>
                <td>{{done.device_type}}</td>
                <td>{{done.request_date}}</td>

              
            </tr>
            
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <tr><p>لا توجد طلبات</p></tr>
    {% endif %}
</div>
</div>

</body>
</html>

{% endblock %}

ItProject/itsupport/templates/itsupport/request_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}



</head>
<body>

    {% if request_detail %}
<div class="custom-container">
<div class="row">
    <div class="col-12 col-md-6">
        
        <div class="label">مستلم الطلب</div>
        <div class="value mb-3">{{emp.it_employee.first_name}}</div>
        <div class="label">نوع الطلب</div>
        <div class="value mb-3">{{ request_detail.device_type }}</div>

        <div class="label">تفاصيل الطلب</div>
        <div class="value mb-3">{{ request_detail.problem_description }}</div>

        <div class="label">الصورة</div>
        <div class="value mb-3"><img src="{{request_detail.image.url}}" width="150" height="150" alt=""></div>
        
    </div>

    <div class="col-12 col-md-6">
        
        <div class="label">اسم مقدم الطلب</div>
        <div class="value mb-3">{{ request_detail.user.first_name }} {{ request_detail.user.last_name }}</div>

        <div class="label">البريد الإلكتروني</div>
        <div class="value mb-3">{{ request_detail.user.email }}</div>

        <div class="label">رقم الجهاز</div>
        <div class="value mb-3">{{request_detail.device_id}}</div>

        <div class="label">تاريخ الطلب</div>
        <div class="value mb-3">{{ request_detail.request_date }}</div>

        <div class="label">الحالة</div>
        <div class="value mb-3"><span id="status" class="status status-open">{{ request_detail.status }}</span></div>
    </div>
</div>
{% if request.user.is_staff %}
<div class="btn-container">
    {% if request_detail.status == "مفتوح" %}
    <button class="btn-custom" data-bs-toggle="modal" data-bs-target="#confirmReceiveModal">استلام الطلب</button>
    {% elif request_detail.status == 'تحت الإجراء' %}
    <button class="btn btn-custom btn-danger" data-bs-toggle="modal" data-bs-target="#confirmCloseModal">إغلاق الطلب</button>
    {% endif %}
</div>
{% endif %}


</div>
{% if request_detail.status == 'تحت الإجراء' %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    غرفة الشات
                </div>
                <div class="card-body" style="height: 400px; overflow-y: auto;">
                    <!-- الرسائل -->
                     <div class="row">
                        <div class="col-6" >
                            {% for chat in it_chat %}
                            <div class="d-flex justify-content-start mb-3">
                                <div class="p-3 bg-light rounded border">
                                    <small class="text-muted">{{ chat.user.first_name }}:</small>
                                    <p class="mb-0">{{ chat.content }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                        <div class="col-6" >
                            {% for chat in user_chat %}
                            <div class="d-flex justify-content-end mb-3">
                                <div class="p-3 bg-primary text-white rounded border">
                                    <small class="text-muted">{{ chat.user.first_name }}:</small>
                                    <p class="mb-0">{{ chat.content }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        

                     </div>

                </div>
                <div class="card-footer">
                    <form action="{% url 'itsupport:chating' request_detail.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="content" class="form-control" placeholder="اكتب رسالتك..." required>
                            <button class="btn btn-primary" type="submit">إرسال</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}


<!-- Modal for Closing Request -->
<div class="modal fade" id="confirmCloseModal" tabindex="-1" aria-labelledby="confirmCloseModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="confirmCloseModalLabel">تأكيد إغلاق الطلب</h5>
        </div>
        <div class="modal-body">
            هل أنت متأكد من إغلاق الطلب؟
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">لا</button>
            <form action="{% url 'itsupport:close_order' request_detail.id  %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">نعم</button>
            </form>
        </div>
    </div>
</div>
</div>

<!-- Modal for Receiving Request -->
<div class="modal fade" id="confirmReceiveModal" tabindex="-1" aria-labelledby="confirmReceiveModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="confirmReceiveModalLabel">تأكيد استلام الطلب</h5>
        </div>
        <div class="modal-body">
            هل أنت متأكد من استلام الطلب؟
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">لا</button>
            <form action="{% url 'itsupport:request_detail_view' request_detail.id  %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">نعم</button>
            </form>
        </div>
    </div>
</div>
</div>



{% elif prenter_detail %}


<div class="custom-container">
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="label">مستلم الطلب</div>
            <div class="value mb-3">{{emp.it_employee.first_name}}</div>
            <div class="label">نوع الطابعة</div>
            <div class="value mb-3">{{ prenter_detail.printer_type }}</div>
    
            <div class="label">رقم الطابعة</div>
            <div class="value mb-3">{{ prenter_detail.printer_id }}</div>
    
            <div class="label">الصورة</div>
            <div class="value mb-3"><img src="{{prenter_detail.image.url}}" width="150" height="150" alt=""></div>
            
        </div>
    
        <div class="col-12 col-md-6">
            <div class="label">اسم مقدم الطلب</div>
            <div class="value mb-3">{{ prenter_detail.user.first_name }} {{ prenter_detail.user.last_name }}</div>
    
            <div class="label">البريد الإلكتروني</div>
            <div class="value mb-3">{{ prenter_detail.user.email }}</div>
    
            <div class="label">رقم الحبر</div>
            <div class="value mb-3">{{prenter_detail.ink_id}}</div>
    
            <div class="label">تاريخ الطلب</div>
            <div class="value mb-3">{{ prenter_detail.request_date }}</div>
    
            <div class="label">الحالة</div>
            <div class="value mb-3"><span id="status" class="status status-open">{{ prenter_detail.status }}</span></div>
        </div>
    </div>
    {% if request.user.is_staff %}
    <div class="btn-container">
        {% if prenter_detail.status == "مفتوح" %}
        <button class="btn-custom" data-bs-toggle="modal" data-bs-target="#confirmReceiveModal">استلام الطلب</button>
        {% elif prenter_detail.status == 'تحت الإجراء' %}
        <button class="btn  btn-danger" data-bs-toggle="modal" data-bs-target="#confirmCloseModal">إغلاق الطلب</button>
        {% endif %}
    </div>
    {% endif %}
    

    </div>
    {% if prenter_detail.status == 'تحت الإجراء' %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        غرفة الشات
                    </div>
                    <div class="card-body" style="height: 400px; overflow-y: auto;">
                        <!-- الرسائل -->
                         <div class="row">
                            <div class="col-6" >
                                {% for chat in it_chat %}
                                <div class="d-flex justify-content-start mb-3">
                                    <div class="p-3 bg-light rounded border">
                                        <small class="text-muted">{{ chat.user.first_name }}:</small>
                                        <p class="mb-0">{{ chat.content }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
    
                            <div class="col-6" >
                                {% for chat in user_chat %}
                                <div class="d-flex justify-content-end mb-3">
                                    <div class="p-3 bg-primary text-white rounded border">
                                        <small class="text-muted">{{ chat.user.first_name }}:</small>
                                        <p class="mb-0">{{ chat.content }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            
    
                         </div>
    
                    </div>
                    <div class="card-footer">
                        <form action="{% url 'itsupport:chating' prenter_detail.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" name="content" class="form-control" placeholder="اكتب رسالتك..." required>
                                <button class="btn btn-primary" type="submit">إرسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    
    <!-- Modal for Closing Request -->
    <div class="modal fade" id="confirmCloseModal" tabindex="-1" aria-labelledby="confirmCloseModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmCloseModalLabel">تأكيد إغلاق الطلب</h5>
            </div>
            <div class="modal-body">
                هل أنت متأكد من إغلاق الطلب؟
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">لا</button>
                <form action="{% url 'itsupport:close_order' prenter_detail.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">نعم</button>
                </form>
            </div>
        </div>
    </div>
    </div>
    
    <!-- Modal for Receiving Request -->
    <div class="modal fade" id="confirmReceiveModal" tabindex="-1" aria-labelledby="confirmReceiveModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmReceiveModalLabel">تأكيد استلام الطلب</h5>
            </div>
            <div class="modal-body">
                هل أنت متأكد من استلام الطلب؟
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">لا</button>
                <form action="{% url 'itsupport:request_detail_view' prenter_detail.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">نعم</button>
                </form>
            </div>
        </div>
    </div>
    </div>


{% endif %}










{% endblock %}

ItProject/itsupport/templates/itsupport/support_request.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}

<!-- Button trigger modal -->
<div class="container mt-5">
  <div class="row d-flex justify-content-center ">
    <div class="col-6">
      <button type="button" class="btn shadow bg-light  h-100" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <div class ="p-3"> <img src="{% static 'images/maint2.png' %}" class="img-fluid mb-4 border" width="150" height="100" alt="..."></div>
        الصيانة
      </button>
    </div>

    <div class="col-6">
      <button type="button" class="btn shadow bg-light  h-100" data-bs-toggle="modal" data-bs-target="#printerModal">
        <div class ="p-3"> <img src="{% static 'images/maint3.png' %}" class="img-fluid mb-4 border" width="150" height="100" alt="..."></div>
        أحبار
      </button>
    </div>
  </div>
  
  <!-- Modal: تقرير الصيانة -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">تقرير الصيانة</h1>
      
        </div>

        <form action="{% url 'itsupport:support_request' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}


          <div class="modal-body">
            <!-- نوع الجهاز -->
            <div class="mb-3">
              <label for="device_type" class="form-label">أختر نوع الجهاز</label>
              <select class="form-select" id="device_type" name="device_type" required>
             
                <option value="كمبيوتر مكتبي">كمبيوتر مكتبي</option>
                <option value="لابتوب">لابتوب</option>
                <option value="سكانر">سكانر</option>
                <option value="طابعة">طابعة</option>
              </select>
            </div>

            <!-- رقم الجهاز -->
            <div class="mb-3">
              <label for="device_id" class="form-label">رقم الجهاز</label>
              <input type="text" class="form-control" id="device_id" name="device_id" required>
            </div>
            
            <!-- وصف المشكلة -->
            <div class="mb-3">
              <label for="problem_description" class="form-label">وصف المشكلة</label>
              <textarea class="form-control" id="problem_description" name="problem_description" rows="3" required></textarea>
            </div>
            
            <!-- المرفقات -->
            <div class="mb-3">
              <label for="image" class="form-label">المرفقات</label>
              <input type="file" class="form-control" id="image" name="image" >
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">أغلاق</button>
            {% if msg %}
            <p  class="alert alert-danger">{{msg}}</p>
            {% else %}
            <button type="submit" class="btn btn-primary">إرسال</button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Modal: تقرير حبر -->
  <div class="modal fade" id="printerModal" tabindex="-1" aria-labelledby="printerModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="printerModalLabel">طلب حبر </h1>
     
        </div>

        <form action="{% url 'itsupport:add_printer_request' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="modal-body">
            <!-- نوع الطابعة -->
            <div class="mb-3">
              <label for="printer_type" class="form-label">نوع الطابعة</label>
              <input type="text" class="form-control" id="printer_type" name="printer_type" required>
            </div>

            <!-- رقم الطابعة -->
            <div class="mb-3">
              <label for="printer_id" class="form-label">رقم الطابعة</label>
              <input type="text" class="form-control" id="printer_id" name="printer_id" required>
            </div>

            <!-- رقم الحبر -->
            <div class="mb-3">
              <label for="ink_id" class="form-label">رقم الحبر</label>
              <input type="text" class="form-control" id="ink_id" name="ink_id" required>
            </div>
            
            <!-- المرفقات -->
            <div class="mb-3">
              <label for="image" class="form-label">المرفقات</label>
              <input type="file" class="form-control" id="image" name="image" >
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">أغلاق</button>
            <button type="submit" class="btn btn-primary">إرسال</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}