ItProject/ItProject/urls.py
from django.contrib import admin
from django.urls import path,include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
    path("user/",include("user.urls")),
    path("support/",include("itsupport.urls")),
]+ static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)   

ItProject/itsupport/urls.py
from django.urls import path
from .import views
app_name ="itsupport"


urlpatterns =[
    path("support/request/",views.support_request, name="support_request"),
    path("user/request/",views.user_request_view,name="user_request_view"),
    path("my/order/",views.my_order,name="my_order"),
    path("add/prenter/request",views.add_printer_request,name="add_printer_request"),
    path("request/detail/<request_id>",views.request_detail_view,name="request_detail_view"),
    path("close/order/<request_id>",views.close_order,name="close_order"),
    path("on/workv/",views.on_work_view ,name="on_work_view"),
    path("done/work/",views.done_work_view,name="done_work_view"),
    path("chating/<request_id>/",views.chating,name="chating")
]

ItProject/main/urls.py
from django.urls import path
from .import views
app_name = "main"


urlpatterns =[
    path("",views.home_view,name="home_view"),

]

ItProject/user/urls.py
from django.urls import path
from .import views


app_name="user"

urlpatterns =[
    path("user/login",views.login_view,name="login_view"),
    path("logout/",views.logout_view,name="logout_view"),
    path("add/user/",views.add_user_view,name="add_user_view")
    
]

ItProject/main/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest


# Create your views here.


def home_view(request:HttpRequest):        
   
    return render(request,"main/home.html")

ItProject/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <style>
        *{
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div dir="rtl" class="container-fluid">
            <img class="img-fluid" src="{% static 'images/logo.jpeg' %}" width="150" height="100" alt="">
            <a class="navbar-brand" href="{% url 'main:home_view' %}">الدعم الفني</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="تبديل التنقل">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'user:add_user_view' %}">إضافة مستخدمين</a>
                    </li>
                    {% endif %}
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#">الميزات</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">التسعير</a>
                    </li> -->
                    {% if request.user.is_authenticated%}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            القائمة
                        </a>
                        
                        {% if not request.user.is_staff %}
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'itsupport:support_request' %}">رفع طلب</a></li>
                            <li><a class="dropdown-item" href="{% url 'itsupport:my_order' %}">طلباتي</a></li>
                            
                        </ul>
                        {%elif request.user.is_staff %}
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'itsupport:user_request_view' %}">طلبات الدعم</a></li>
                            <li><a class="dropdown-item" href="{% url 'itsupport:on_work_view' %}">جاري العمل عليها</a></li>
                            <li><a class="dropdown-item" href="{% url 'itsupport:done_work_view' %}">منتهي</a></li>
                        </ul>
                    </li>
                </ul>
                {% endif %}
                {% if request.user.is_authenticated%}
                <li class="nav-link">مرحبا {{request.user.username}}</li>

                <a class="navbar-brand" href="{% url 'user:logout_view' %}"><i class="bi bi-box-arrow-right"></i></a>
                
                {% endif %}

                {% endif %}
                
                
            </div>

        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}

        {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

ItProject/main/templates/main/home.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}



<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 ">
            <img src="{% static 'images/main_logo.png' %}" class="img-fluid" alt="Responsive image">
        </div>
    </div>
</div>

{% if not request.user.is_authenticated %}
<div class="row d-flex justify-content-center mt-3 ">
    <a href="{% url 'user:login_view' %}"  class=" d-flex justify-content-center  btn btn-outline-success mt-1 border border-0 shadow p-2  rounded w-25 ">التسجيل</a>
    </div>

{% endif %}


{%endblock%}

ItProject/main/templates/main/it_help.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}

<div class="vh-100">

</div> 
<br>
{% endblock %}